[build]
  publish = "src"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#static"
  command = "echo 'Dev server ready'"
  targetPort = 8888
  port = 8888
  autoLaunch = true
